### ISSUE TITLE
mprotect: EACCES

### ISSUE THREAD

**Issue by djs55** [mirage/mirage-solo5#22]
Running the `speaking_clock` example from [mirage-skeleton](https://github.com/mirage/mirage-skeleton/tree/master/device-usage/clock) fails on my freshly-installed `alpine-3.6.1` machine with `mprotect:...EACCES` according to `strace`.

The binary successfully
- opens `/dev/kvm`
- opens `speaking_clock.ukvm`
- reads the ELF contents from `speaking_clock.ukvm`
- fails the `mprotect`

This is with v0.2.1 of `mirage-solo5` if that's relevant.

**Comment by mato** [comment]
This should probably be reported under Solo5/solo5 as it's likely to be an `ukvm` issue.

My guess is it's a security feature of Alpine disallowing adding `PROT_EXEC` to existing segments. Do you get the same behaviour if you pin `solo5-kernel-ukvm` to git master?

**Comment by djs55** [comment]
Thanks -- I've retested with git master and it still reproduces. I've made a Solo5/solo5 issue as you suggest.

For my own testing I'll switch to a less hardened kernel, assuming that's the problem.

**Comment by mato** [comment]
> For my own testing I'll switch to a less hardened kernel, assuming that's the problem.

Thanks for reporting; I would also assume that the hardened kernel is the
problem. Are you running ukvm as root, or just as a user with access to
/dev/kvm?

**Comment by djs55** [comment]
I ran everything on alpine from a root shell. On Ubuntu I've been building as a user and using `sudo` to launch the unikernel.

**Comment by mato** [comment]
> I ran everything on alpine from a root shell. On Ubuntu I've been building as a user and using `sudo` to launch the unikernel.

Just FYI, normally you don't need root to run ukvm, write access to
/dev/kvm is enough (e.g. via a kvm group). You do of course need root to
set up the tap interface for ukvm to use.
